global using Microsoft.JSInterop;
global using Microsoft.AspNetCore.Components;
global using CommonBasicLibraries.CollectionClasses;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
